[keybindings]
next_panel = ["l", "Right", "Tab"]
prev_panel = ["h", "Left", "BackTab"]
move_up = ["k", "Up"]
move_down = ["j", "Down"]
mark_read = [" "]
new_message = ["c", "n"]
reply = ["r"]
delete = ["d"]
archive = ["Backspace", "a"]
quit = ["q"]

[signatures]
new_message = """
JT Smith"""

reply = """

Best,
Your Name"""

